Repository RomainBoiret/Teddy_Bot.js, pull requests merged in 2023-12, with the labels that each got.

#2 Add kick and ban
  Teddy bot/Commandes/ban.js
  Teddy bot/Commandes/kick.js
  Teddy bot/Commandes/ping.js
  Teddy bot/Events/interactionCreate.js
  Teddy bot/Loaders/loadSlashCommands.js
Labels: enhancement

#3 Add mute command
  Teddy bot/Commandes/mute.js
  Teddy bot/node_modules/.package-lock.json
  Teddy bot/node_modules/ms/index.js
  Teddy bot/node_modules/ms/license.md
  Teddy bot/node_modules/ms/package.json
  Teddy bot/node_modules/ms/readme.md
  Teddy bot/package-lock.json
  Teddy bot/package.json
Labels: enhancement

#4 Ajout du fichier README.md
  README.md
Labels: documentation

#5 Correction d'un bug sur mute
  Teddy bot/Commandes/kick.js
  Teddy bot/Commandes/mute.js
Labels: bug

#6 add unmute command
  Teddy bot/Commandes/mute.js
  Teddy bot/Commandes/unmute.js
Labels: enhancement

#7 Create unban.js
  Teddy bot/Commandes/unban.js
Labels: enhancement

#8 Create clear.js
  Teddy bot/Commandes/clear.js
Labels: enhancement
